sonata_block:
    default_contexts: [admin]
    blocks:
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_intl:
    timezone:
        default: America/Santiago

sonata_admin:
    title:      Administración DriveSigner
    title_logo: /bundles/app/img/logo.png
    options:
        use_select2: true
    templates:
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
        layout:              AppBundle:Admin:standard_layout.html.twig
        user_block:          AppBundle:Admin:user_block.html.twig
    dashboard:
        groups:
          usuario:
            icon:  '<i class="fa fa-cogs"></i>'
            label: Administración
            items:
                - admin.cliente
                - admin.usuario
                - admin.configuracion
                - admin.usuario_log