AppBundle\Entity\Transaccion:
  type: entity
  table: transaccion
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    createdAt:
      type: datetime
      column: created_at
    updatedAt:
      type: datetime
      column: updated_at
      nullable: true
  manyToOne:
    usuario:
      targetEntity: AppBundle\Entity\Usuario
      inversedBy: transacciones
      joinColumn:
        name: id_usuario
        referencedColumnName: id
        nullable: false
  oneToMany:
    detalles:
      targetEntity: AppBundle\Entity\DetalleTransaccion
      mappedBy: transaccion